---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: groundhog2k
  namespace: default
spec:
  interval: 1m0s
  url: https://groundhog2k.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  chart:
    spec:
      chart: wordpress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
  interval: 5m0s
  timeout: 1m0s
  values:
    storage:
      requestedSize: 10Gi
    mariadb:
      storage:
        requestedSize: 10Gi
      enabled: true
      allowEmptyRootPassword: false
      settings:
        rootPassword: YOUR_PASSWORD
      userDatabase:
        name: wordpress
        user: wordpress
        password: YOUR_PASSWORD
